"""discografia: anade catalog_number, credits y notes a Edition

Revision ID: 001dc1a49b36
Revises: 614fd09c15a2
Create Date: 2026-07-28 17:24:01.559475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001dc1a49b36'
down_revision: Union[str, Sequence[str], None] = '614fd09c15a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('catalog_number', sa.String(length=100), nullable=True))
    op.add_column('editions', sa.Column('credits', sa.Text(), nullable=True))
    op.add_column('editions', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('editions', 'notes')
    op.drop_column('editions', 'credits')
    op.drop_column('editions', 'catalog_number')
    # ### end Alembic commands ###
