"""auth: anade is_super_admin a User

Revision ID: 0c25cd68b89e
Revises: 1bd15037e068
Create Date: 2026-07-27 17:19:06.473215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c25cd68b89e'
down_revision: Union[str, Sequence[str], None] = '1bd15037e068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default: la tabla `users` ya tiene filas (a diferencia de cuando se
    # creo `is_admin` en la migracion inicial, con la tabla recien creada y
    # vacia). Sin un valor por defecto, Postgres no sabe que poner en las filas
    # existentes de una columna NOT NULL nueva y la migracion fallaria.
    op.add_column(
        'users',
        sa.Column(
            'is_super_admin',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin')
    # ### end Alembic commands ###
