"""add description to releases

Revision ID: 590d74c493ce
Revises: 35c4805f0c01
Create Date: 2026-08-04 19:37:23.160250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590d74c493ce'
down_revision: Union[str, Sequence[str], None] = '35c4805f0c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releases', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'description')
    # ### end Alembic commands ###
