"""recuperacion de contrasena: codigo en users y tabla de intentos

Revision ID: 5f145a02d004
Revises: 8cbfa5b0ea40
Create Date: 2026-08-07 14:45:46.757700

Soporte para POST /auth/password-reset/{request,confirm} (ver
app/modules/auth/service.py). Mismo patron que la verificacion de email
(migracion 8cbfa5b0ea40): un par hash+caducidad en `users` para el codigo
PENDIENTE, sobrescribible; y una tabla de intentos fallidos para el limite en
ventana movil de 24h.

`password_reset_attempts.identifier` (no `user_id`) es la diferencia clave:
este flujo va SIN autenticar y la cuenta puede no existir, asi que el limite
de intentos tiene que poder contarse igualmente por el `username_or_email`
tal cual se envio, sin depender de una FK a `users`. Todas las columnas
nuevas son nullable (o tienen su propio default a nivel de tabla): no hace
falta `server_default` ni backfill, a diferencia de `email_verified` en la
migracion anterior.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f145a02d004'
down_revision: Union[str, Sequence[str], None] = '8cbfa5b0ea40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_attempts_identifier'), 'password_reset_attempts', ['identifier'], unique=False)
    op.add_column('users', sa.Column('password_reset_code_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_reset_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_code_expires_at')
    op.drop_column('users', 'password_reset_code_hash')
    op.drop_index(op.f('ix_password_reset_attempts_identifier'), table_name='password_reset_attempts')
    op.drop_table('password_reset_attempts')
    # ### end Alembic commands ###
