"""discografia: anade format a Edition

Revision ID: 614fd09c15a2
Revises: 0c25cd68b89e
Create Date: 2026-07-28 17:15:07.636102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614fd09c15a2'
down_revision: Union[str, Sequence[str], None] = '0c25cd68b89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('format', sa.Enum('vinyl', 'cd', 'single', 'maxi_single', 'cd_single', 'cassette', name='editionformat', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('editions', 'format')
    # ### end Alembic commands ###
