"""auth: anade theme_preference a User

Revision ID: 705c818995c0
Revises: 001dc1a49b36
Create Date: 2026-07-28 17:48:03.492127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705c818995c0'
down_revision: Union[str, Sequence[str], None] = '001dc1a49b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default: la tabla `users` ya tiene filas (mismo gotcha que
    # is_super_admin). Sin un valor por defecto, Postgres no sabe que poner en
    # las filas existentes de una columna NOT NULL nueva y la migracion falla.
    op.add_column(
        'users',
        sa.Column(
            'theme_preference',
            sa.Enum('light', 'dark', 'system', name='themepreference', native_enum=False),
            nullable=False,
            server_default=sa.text("'system'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme_preference')
    # ### end Alembic commands ###
