"""verificacion de email: campos en users y tabla de intentos

Revision ID: 8cbfa5b0ea40
Revises: f0ee802141d7
Create Date: 2026-08-07 13:18:13.454615

Soporte para verificacion de email por codigo numerico (POST
/auth/verify-email/request y /confirm, ver app/core/email.py y
app/modules/auth/service.py).

`email_verified` necesita `server_default='false'`: la tabla `users` ya tiene
filas (mismo gotcha que `username_is_default`/`is_admin`). Tras crear la
columna se hace un backfill: las cuentas que YA tienen `google_id` (creadas o
vinculadas por Google) pasan a `email_verified=true`, porque su email ya fue
verificado por Google en su momento (ver `google_login`/`link_google_account`,
que exigen `email_verified: true` en el ID token) -- no tendria sentido
pedirles reverificar algo que ya se comprobo.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbfa5b0ea40'
down_revision: Union[str, Sequence[str], None] = 'f0ee802141d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('email_verification_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_attempts_user_id'), 'email_verification_attempts', ['user_id'], unique=False)
    op.add_column(
        'users',
        sa.Column(
            'email_verified',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False,
        ),
    )
    op.add_column('users', sa.Column('email_verification_code_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('email_verification_code_expires_at', sa.DateTime(timezone=True), nullable=True))

    # Backfill: las cuentas ya vinculadas a Google tienen el email verificado
    # desde siempre (Google lo exige antes de vincular/dar de alta).
    op.execute("UPDATE users SET email_verified = true WHERE google_id IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_code_expires_at')
    op.drop_column('users', 'email_verification_code_hash')
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_email_verification_attempts_user_id'), table_name='email_verification_attempts')
    op.drop_table('email_verification_attempts')
    # ### end Alembic commands ###
