"""colecciones de ediciones (Collection + tabla puente)

Revision ID: 904b404a095b
Revises: 5f145a02d004
Create Date: 2026-08-07 16:16:29.033042

Fase 6 del backlog: agrupar ediciones de OBRAS DISTINTAS bajo un nombre comun
(p. ej. "Remasterizaciones HDCD"), navegable desde /api/v1/discography/collections.

`collection_editions` es una tabla puente de Core (sin PK propio, clave
compuesta collection_id+edition_id), no una clase ORM: no tiene ningun campo
extra (el orden dentro de una coleccion se calcula siempre por
Edition.release_date, nunca se guarda una posicion manual aqui) -- ver
app/modules/discography/models.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904b404a095b'
down_revision: Union[str, Sequence[str], None] = '5f145a02d004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collection_editions',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'edition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_editions')
    op.drop_table('collections')
    # ### end Alembic commands ###
