"""discografia: introduce Edition entre Release y Track

Revision ID: b78f7d9b03bc
Revises: fc766ae7e10c
Create Date: 2026-07-26 17:01:21.910282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78f7d9b03bc'
down_revision: Union[str, Sequence[str], None] = 'fc766ae7e10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('edition_name', sa.String(length=200), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editions_release_id'), 'editions', ['release_id'], unique=False)
    op.create_index('uq_editions_release_primary', 'editions', ['release_id'], unique=True, postgresql_where=sa.text('is_primary'), sqlite_where=sa.text('is_primary'))
    op.drop_column('releases', 'release_date')
    op.add_column('tracks', sa.Column('edition_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tracks_release_id'), table_name='tracks')
    op.drop_constraint(op.f('uq_tracks_release_position'), 'tracks', type_='unique')
    op.create_index(op.f('ix_tracks_edition_id'), 'tracks', ['edition_id'], unique=False)
    op.create_unique_constraint('uq_tracks_edition_position', 'tracks', ['edition_id', 'position'])
    op.drop_constraint(op.f('tracks_release_id_fkey'), 'tracks', type_='foreignkey')
    op.create_foreign_key(None, 'tracks', 'editions', ['edition_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tracks', 'release_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('release_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.create_foreign_key(op.f('tracks_release_id_fkey'), 'tracks', 'releases', ['release_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_tracks_edition_position', 'tracks', type_='unique')
    op.drop_index(op.f('ix_tracks_edition_id'), table_name='tracks')
    op.create_unique_constraint(op.f('uq_tracks_release_position'), 'tracks', ['release_id', 'position'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tracks_release_id'), 'tracks', ['release_id'], unique=False)
    op.drop_column('tracks', 'edition_id')
    op.add_column('releases', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index('uq_editions_release_primary', table_name='editions', postgresql_where=sa.text('is_primary'), sqlite_where=sa.text('is_primary'))
    op.drop_index(op.f('ix_editions_release_id'), table_name='editions')
    op.drop_table('editions')
    # ### end Alembic commands ###
