"""foro de discusion (ForumThread, ForumComment)

Revision ID: b8d9caca4cde
Revises: 904b404a095b
Create Date: 2026-08-08 17:41:15.651096

Fase 7 del backlog: foro atado al catalogo (/api/v1/forum/threads). Ver
app/modules/forum/models.py.

`entity_id` en `forum_threads` NO lleva FK real: puede apuntar a
`releases.id` o a `editions.id` segun `entity_type`, y una FK no puede
apuntar a "una tabla u otra" -- se valida en el service
(discography.service.release_exists/edition_exists), no en el esquema.
`author_id` (en ambas tablas) tampoco tiene relationship ORM hacia `users`,
solo la FK a nivel de BD: el modulo de foro no importa modelos de auth (ver
docstring de models.py).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d9caca4cde'
down_revision: Union[str, Sequence[str], None] = '904b404a095b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('release', 'edition', 'discography', name='ck_forum_threads_entity_type', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'closed', name='ck_forum_threads_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_threads_author_id'), 'forum_threads', ['author_id'], unique=False)
    op.create_table('forum_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_comments_author_id'), 'forum_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_forum_comments_thread_id'), 'forum_comments', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_comments_thread_id'), table_name='forum_comments')
    op.drop_index(op.f('ix_forum_comments_author_id'), table_name='forum_comments')
    op.drop_table('forum_comments')
    op.drop_index(op.f('ix_forum_threads_author_id'), table_name='forum_threads')
    op.drop_table('forum_threads')
    # ### end Alembic commands ###
