"""anade google_id a users

Revision ID: e0acec4b4840
Revises: 5677cd83477c
Create Date: 2026-08-06 17:55:31.135983

Soporte para login/registro con Google (POST /auth/google). `google_id`
guarda el `sub` del ID token (identificador estable de la cuenta de Google,
no el email: el email puede cambiar, el `sub` no). Nullable porque la
mayoria de usuarios siguen entrando por contrasena; unique porque una misma
cuenta de Google no puede vincularse a dos usuarios distintos.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0acec4b4840'
down_revision: Union[str, Sequence[str], None] = '5677cd83477c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
