"""anade username_is_default a users

Revision ID: f0ee802141d7
Revises: e0acec4b4840
Create Date: 2026-08-06 18:44:59.212947

Soporte para el username provisional de las altas por Google (ver
service.google_login / update_profile): username_is_default=True marca que
el username es aleatorio y aun no lo eligio la persona, lo que le permite
cambiarlo UNA vez por PATCH /auth/me.

`server_default='false'` es obligatorio: la tabla `users` ya tiene filas (no
es una migracion inicial en tabla vacia como is_admin en su dia), y la
columna es NOT NULL -> sin el default, Postgres no sabria que poner en las
filas existentes.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ee802141d7'
down_revision: Union[str, Sequence[str], None] = 'e0acec4b4840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users',
        sa.Column(
            'username_is_default',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username_is_default')
    # ### end Alembic commands ###
